### ISSUE TITLE
re: Mouse battery

### ISSUE THREAD

**Issue by migabc** [matryer/bitbar-plugins#901]
FAO: (@alexandregz)

Hi, After updating to High Sierra I now get these errors:

<img width="1047" alt="screen shot 2017-11-03 at 8 04 43 am" src="https://user-images.githubusercontent.com/25421603/32364609-b3d8567e-c06d-11e7-957a-cbddcf2247ae.png">

This is also happing with the "Battery Apple Bluetooth keyboard" plugin

Is there a way to fix this?
Thanks.

**Comment by alexandregz** [comment]
Hi @migabc 

I checked with High Sierra and with Mouse and Keyboard plugins and is fine:

alex@vosjod:~/Development/bitbar/bitbar-plugins/Enabled(master)$ ./keyboard-system_profiler.1m.rb
Keyboard: 4%
alex@vosjod:~/Development/bitbar/bitbar-plugins/Enabled(master)$ ./mouse.1m.sh
Mouse: 41%

![captura de pantalla 2018-01-05 a las 15 27 10](https://user-images.githubusercontent.com/1374718/34613195-31e4e8f2-f22d-11e7-9c02-c335bfd9d11d.png)

**Comment by migabc** [comment]
I'm using na iMac 27" 2017.
It shows the keyboard and mouse battery percentage but it also shows those errors I mentioned above.
It was working OK before the upgrade (when I had macOS Sierra)

**Comment by atadams** [comment]
I was getting the errors too. For keyboard-system_profiler.1m.rb, changing

```output = YAML.load(`system_profiler SPBluetoothDataType`);```

to

```output = YAML.load(`system_profiler SPBluetoothDataType 2>/dev/null`);```

resolved the errors.

**Comment by migabc** [comment]
I tried to make that change but I get a "poxix_spawn: error 1" as soon as I edit the file.
I rolled back the change but I still get the same error.
I'm using TextEdit (plain Text).
Am I missing something?

**Comment by alexandregz** [comment]
👍
